# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: calculate.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='calculate.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x0f\x63\x61lculate.proto\"\"\n\x04Nums\x12\x0c\n\x04num1\x18\x01 \x01(\x05\x12\x0c\n\x04num2\x18\x02 \x01(\x05\"\x15\n\x03Sum\x12\x0e\n\x06result\x18\x01 \x01(\x05\x32!\n\tCalculate\x12\x14\n\x03\x61\x64\x64\x12\x05.Nums\x1a\x04.Sum\"\x00\x62\x06proto3')
)




_NUMS = _descriptor.Descriptor(
  name='Nums',
  full_name='Nums',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='num1', full_name='Nums.num1', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='num2', full_name='Nums.num2', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=19,
  serialized_end=53,
)


_SUM = _descriptor.Descriptor(
  name='Sum',
  full_name='Sum',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='result', full_name='Sum.result', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=55,
  serialized_end=76,
)

DESCRIPTOR.message_types_by_name['Nums'] = _NUMS
DESCRIPTOR.message_types_by_name['Sum'] = _SUM
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Nums = _reflection.GeneratedProtocolMessageType('Nums', (_message.Message,), dict(
  DESCRIPTOR = _NUMS,
  __module__ = 'calculate_pb2'
  # @@protoc_insertion_point(class_scope:Nums)
  ))
_sym_db.RegisterMessage(Nums)

Sum = _reflection.GeneratedProtocolMessageType('Sum', (_message.Message,), dict(
  DESCRIPTOR = _SUM,
  __module__ = 'calculate_pb2'
  # @@protoc_insertion_point(class_scope:Sum)
  ))
_sym_db.RegisterMessage(Sum)



_CALCULATE = _descriptor.ServiceDescriptor(
  name='Calculate',
  full_name='Calculate',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=78,
  serialized_end=111,
  methods=[
  _descriptor.MethodDescriptor(
    name='add',
    full_name='Calculate.add',
    index=0,
    containing_service=None,
    input_type=_NUMS,
    output_type=_SUM,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_CALCULATE)

DESCRIPTOR.services_by_name['Calculate'] = _CALCULATE

# @@protoc_insertion_point(module_scope)
